spring:
  application:
    name: gateway
  profiles:
    active: dev
server:
  port: ${SERVICE_PORT:8080}

eureka:
  instance:
    prefer-ip-address: true
    hostname: 172.17.0.1
  client:
    registerWithEureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://127.0.0.1:8000}/eureka/

filter-properties:
  include-url-patterns:
    - actuator/health
    - actuator/routes
    - /test/*

zuul:
  sensitive-headers:
    - Cookie,Set-Cookie
  host:
    connect-timeout-millis: 360000
    socket-timeout-millis: 360000
  routes:
    test-api:
      serviceId: test-api
      path: /test-api/**
      stripPrefix: true