spring:
  application:
    name: gateway
  profiles:
    active: local
server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    registerWithEureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8000/eureka/

filter-properties:
  include-url-patterns:
    - actuator/health
    - actuator/routes
    - /test/*

zuul:
  sensitive-headers:
    - Cookie,Set-Cookie
  host:
    connect-timeout-millis: 360000
    socket-timeout-millis: 360000
  routes:
    test-api:
      serviceId: test-api
      path: /test-api/**
      stripPrefix: true